image: $CI_REGISTRY_IMAGE

stages:
  - test
  - build

format:
  stage: test
  extends:
    - ".go"
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

BuildDesktop:
  stage: build
  extends:
    - ".go"
  script:
    - ./build_desktop.sh
  artifacts:
    paths:
      - ./desktop

BuildAndroidLibrary:
  stage: build
  extends:
    - ".go"
  script:
    - ./build_android.sh

  artifacts:
    paths:
      - ./android

BuildiOSFramework:
  stage: build
  tags: [ macos11 ]
  extends:
    - ".go"
  script:
    - ./build_ios.sh
  artifacts:
    paths:
      - ./iOS

".go":
  stage: build
  before_script:
    - apk -U upgrade
    - apk --no-cache add curl
    - apk add go
    - export PATH=$PATH:~/go/bin