image: $CI_REGISTRY_IMAGE

stages:
  - test
  - build

format:
  stage: test
  extends:
    - ".go"
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)
   
BuildAndroidLibrary:
  stage: build
  extends:
    - ".go"
    - ".android"
  script:
    - gomobile init  
    - mkdir -p android
    - cd wstunnel
    - gomobile bind -o ../android/wstunnel.aar  -javapkg com.windscribe.websockettunnel
    
  artifacts:
    paths:
      - android

BuildiOSFramework:
  stage: build
  tags: [macos11]
  before_script:
    - go install golang.org/x/mobile/cmd/gomobile@latest  
    - export PATH=$PATH:~/go/bin
  script:
    - gomobile init  
    - mkdir -p iOS
    - cd wstunnel
    - gomobile bind -target ios/arm64 -o ../iOS/wstunnel.xcframework
    - cd ../
    
  artifacts:
    paths:
      - ./iOS

".go":
    stage: build
    before_script:
      - apk -U upgrade
      - apk --no-cache add curl
      - apk add go
      - export PATH=$PATH:~/go/bin

".android":
    stage: build
    before_script:
      - apk add go
      - export PATH=$PATH:~/go/bin
      - go install golang.org/x/mobile/cmd/gomobile@latest
      - extras ndk