image: $CI_REGISTRY_IMAGE

stages:
  - test
  - build

#format:
#  stage: test
#  extends:
#    - ".go"
#  script:
#    - go fmt $(go list ./... | grep -v /vendor/)
#    - go vet $(go list ./... | grep -v /vendor/)
#    - go test -race $(go list ./... | grep -v /vendor/)
#
#BuildDesktop:
#  stage: build
#  extends:
#    - ".go"
#  script:
#    - chmod +x build_desktop.sh
#    - ./build_desktop.sh
#  artifacts:
#    paths:
#      - ./build

BuildAndroidLibrary:
  stage: build
  extends:
    - ".go"
    - ".ndk"
  script:
    - ./build_android.sh
  artifacts:
    paths:
      - ./build

#BuildiOSFramework:
#  stage: build
#  tags: [ macos11qt6 ]
#  script:
#    - chmod +x build_ios.sh
#    - ./build_ios.sh
#  artifacts:
#    paths:
#      - ./build

".ndk":
  stage: build
  before_script:
    - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
    - unzip -d android-sdk-linux android-sdk.zip
    - echo y | android-sdk-linux/tools/bin/sdkmanager "ndk;21.3.6528147" >/dev/null
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
    - chmod +x ./gradlew
    - set +o pipefail
    - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
    - set -o pipefail

".go":
  stage: build
  before_script:
    - apk -U upgrade
    - apk --no-cache add curl
    - apk add go
    - export PATH=$PATH:~/go/bin